In [17]:
print('hello')

hello


In [18]:
import numpy as np

print('import done')

import done


In [19]:
arr1 = np.array([1, 2, 3, 4, 5])
print(arr1)

[1 2 3 4 5]


In [20]:
# 1D array
arr2 = np.array([1, 2, 3, 4, 5])
arr2.reshape(1, 5)

array([[1, 2, 3, 4, 5]])

In [21]:
# 2D array
arr3 = np.array([[1, 2, 3], [4, 5, 6]])
print(arr3)
print(arr3.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [22]:
np.arange(0, 10, 2).reshape(5, 1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [23]:
np.ones((3, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [24]:
# identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [25]:
arr = np.array ([
        [1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]
        ])

print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [26]:
# slicing & indexing 
print(arr[0][0])


1


In [27]:
print(arr[2:])
print(arr[1:, 2:])

[[7 8 9]]
[[6]
 [9]]


In [28]:
# modifying array elements
arr[0][0] = 100
print(arr)

[[100   2   3]
 [  4   5   6]
 [  7   8   9]]


In [29]:
# Stats concept -- Normalisation
data = np.array([1, 2, 3, 4, 5])

mean = np.mean(data)
std_dev = np.std(data)

normalised_data = (data - mean) / std_dev
print("normalised data:", normalised_data)

normalised data: [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [30]:
# logical operations
data = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
data > 5 

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [31]:
data[data > 5]

array([ 6,  7,  8,  9, 10])

In [32]:
data[(data >= 5) & (data <= 8)]

array([5, 6, 7, 8])